TESTS WITH ERRORS 
test05_GM_8Puzzle_01 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 130, in test05_GM_8Puzzle_01
    p8.read('puzzle8_top_right_empty.txt')
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\game_master.py", line 134, in read
    for fr in read_tokenize(final_path):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\read.py", line 37, in read_tokenize
    for line in file:
  File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 256: character maps to <undefined>

test06_GM_8Puzzle_02 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 140, in test06_GM_8Puzzle_02
    p8.read('puzzle8_center_empty.txt')
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\game_master.py", line 134, in read
    for fr in read_tokenize(final_path):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\read.py", line 37, in read_tokenize
    for line in file:
  File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 256: character maps to <undefined>

test07_GM_8Puzzle_03 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 157, in test07_GM_8Puzzle_03
    p8.read('puzzle8_top_right_empty.txt')
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\game_master.py", line 134, in read
    for fr in read_tokenize(final_path):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\read.py", line 37, in read_tokenize
    for line in file:
  File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 256: character maps to <undefined>

test08_GM_8Puzzle_04 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 185, in test08_GM_8Puzzle_04
    p8.read('puzzle8_center_empty.txt')
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\game_master.py", line 134, in read
    for fr in read_tokenize(final_path):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\read.py", line 37, in read_tokenize
    for line in file:
  File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 256: character maps to <undefined>

test13_BFS_Hanoi_02 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 52, in runPlayXSteps
    results = self.pool.apply_async(self.playXSteps, [solver, plays]).get(timeout)
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 679, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 296, in test13_BFS_Hanoi_02
    [23, ((5,), (4,), (1, 2, 3))],
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 57, in runPlayXSteps
    raise Exception("Timed out: %s" % inspect.stack()[1][3])
Exception: Timed out: test13_BFS_Hanoi_02

test14_BFS_Hanoi_03 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 52, in runPlayXSteps
    results = self.pool.apply_async(self.playXSteps, [solver, plays]).get(timeout)
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 679, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 314, in test14_BFS_Hanoi_03
    [23, ((1, 4, 5), (), (2, 3))],
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 57, in runPlayXSteps
    raise Exception("Timed out: %s" % inspect.stack()[1][3])
Exception: Timed out: test14_BFS_Hanoi_03

test15_DFS_8Puzzle_01 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 319, in test15_DFS_8Puzzle_01
    p8.read('puzzle8_top_right_empty.txt')
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\game_master.py", line 134, in read
    for fr in read_tokenize(final_path):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\read.py", line 37, in read_tokenize
    for line in file:
  File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 256: character maps to <undefined>

test16_DFS_8Puzzle_02 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 338, in test16_DFS_8Puzzle_02
    p8.read('puzzle8_center_empty.txt')
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\game_master.py", line 134, in read
    for fr in read_tokenize(final_path):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\read.py", line 37, in read_tokenize
    for line in file:
  File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 256: character maps to <undefined>

test17_DFS_8Puzzle_03 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 357, in test17_DFS_8Puzzle_03
    p8.read('puzzle8_center_empty.txt')
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\game_master.py", line 134, in read
    for fr in read_tokenize(final_path):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\read.py", line 37, in read_tokenize
    for line in file:
  File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 256: character maps to <undefined>

test18_BFS_8Puzzle_01 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 376, in test18_BFS_8Puzzle_01
    p8.read('puzzle8_top_right_empty.txt')
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\game_master.py", line 134, in read
    for fr in read_tokenize(final_path):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\read.py", line 37, in read_tokenize
    for line in file:
  File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 256: character maps to <undefined>

test19_BFS_8Puzzle_02 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 395, in test19_BFS_8Puzzle_02
    p8.read('puzzle8_top_right_empty.txt')
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\game_master.py", line 134, in read
    for fr in read_tokenize(final_path):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\read.py", line 37, in read_tokenize
    for line in file:
  File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 256: character maps to <undefined>

test20_BFS_8Puzzle_03 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 414, in test20_BFS_8Puzzle_03
    p8.read('puzzle8_center_empty.txt')
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\game_master.py", line 134, in read
    for fr in read_tokenize(final_path):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\read.py", line 37, in read_tokenize
    for line in file:
  File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 256: character maps to <undefined>

-------------------------------
TESTS FAILED  
test10_DFS_Hanoi_02 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 246, in test10_DFS_Hanoi_02
    [20, ((2,5,), (4,), (1, 3))],
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 55, in runPlayXSteps
    self.assertEqual(results[index], expected)
AssertionError: Tuples differ: ((2, 4, 5), (1,), (1, 3)) != ((5,), (4,), (1, 2, 3))

First differing element 0:
(2, 4, 5)
(5,)

- ((2, 4, 5), (1,), (1, 3))
+ ((5,), (4,), (1, 2, 3))

test12_BFS_Hanoi_01 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 278, in test12_BFS_Hanoi_01
    [22, ((2,), (3,), (1,))],
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 55, in runPlayXSteps
    self.assertEqual(results[index], expected)
AssertionError: Tuples differ: ((2,), (), (1, 3)) != ((), (3,), (1, 2))

First differing element 0:
(2,)
()

- ((2,), (), (1, 3))
+ ((), (3,), (1, 2))

-------------------------------
TESTS SKIPPED 
-------------------------------
